### ISSUE TITLE
AppImage not working

### ISSUE THREAD

**Issue by alojzjakob** [eosrio/simpleos#13]
> ./simpleos-0.5.5-x86_64.appimage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_simpleivbjoA/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

openSUSE Tumbleweed

**Comment by eosrio** [comment]
Thanks for the report, we will look into it

**Comment by alojzjakob** [comment]
No problem,
btw, last release worked fine, if that info helps :)

**Comment by timkb4cq** [comment]
Problem confirmed and still present in 0.5.7
Some searching indicates it's likely a bug in the new version of Electron builder

**Comment by sva-h4cky0** [comment]
unfortunately 0.5.7 has same error.

**Comment by nCABLIBi** [comment]
same here since 0.5.5:
`[blade@localhost Downloads]$ ./simpleos-0.5.7-x86_64.AppImage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_simpleDCeQOn/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
`

**Comment by AllienWorks** [comment]
Manjaro here, same issue. Tried with `0.5.5` and `0.5.7`.

**Comment by eosrio** [comment]
Please test with 0.6.1, appImage should work
